import datetime

class WhatapLocators:
    todays = str(datetime.date.today()).split("-")

    ID = 'input#id_email'
    PW = 'input#id_password'
    OTP = 'input.whatap-ant-input'
    LOGIN = 'input#btn_login'
    LOGIN2 = 'button#validate_otp_token'
    KERIS_APM = '//*[@id="root"]/div/div/div[1]/div/div[4]/div/div[1]/div/div/div[2]/div/div[1]/div/div[2]/div/div[2]'
    KERIS_INFRA = '//*[@id="root"]/div/div/div[1]/div/div[4]/div/div[1]/div/div/div[3]/div/div[1]/div/div[2]/div/div[2]'
    
    APM_ANALYTICS = '//*[@id="root"]/div/div/div[1]/div/div[4]/div/div[3]/div/div/div[3]/a[7]'
    APM_METRICS = '//*[@id="root"]/div/div/div[1]/div/div[4]/div/div[3]/div/div/div[3]/a[8]'
    APM_AGENT = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[1]/div[4]/div[2]/div/div[2]/div[1]/div/div/div/div/button'
    APM_SELECT_AGENT = '/html/body/div[3]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/button'
    APM_ALL_AGENT = '//*[@id="ap"]/div[1]/div/button'
    APM_CLOSE_AGENT = '/html/body/div[3]/div/div[2]/div/div/div[1]/button'
    APM_STIME = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[1]/div[1]/div[2]/div/div/div/div/div[1]/div[1]/div[1]/div/div[6]/input'

    APM_INTERVAL = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[1]/div[2]/div[2]/div/div/div/div'
    APM_COMMON_INTERVAL = '/html/body/div[5]/div/div/div/ul/li[1]'
    APM_USER = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[2]/div[1]/div[2]/div/div[2]/div[6]/button'
    APM_ACTIVE_USER = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[2]/div[1]/div[2]/div/div[2]/div[6]/div/button[1]/span'
    APM_MAX_USER = 'div.counterstyle__info-sc-1s8kj3m-10.dTGKQJ'
    APM_MAX_TIME = 'div.counterstyle__info-sc-1s8kj3m-10.dTGKQp' 

    INFRA_REPORT = '보고서'
    INFRA_DROPBOX = 'span.whatap-ant-select-selection-item'
    INFRA_DAILY_REPORT = '/html/body/div[3]/div/div/div/div[2]/div[1]/div/div/div[3]/div'
    INFRA_DATE = '//*[@id="report_container"]/div[1]/div[2]/div/span/div/input'
    INFRA_DATE_SELECT = f'//*[@title="{".".join(todays)}."]'
    INFRA_STIME = '//*[@id="report_container"]/div[1]/div[3]/div/span/input'
    INFRA_STIME_SELECT = '/html/body/div[5]/div/div/div/div[2]/div[1]/ul/li[4]'
    INFRA_STIME_SELECT2 = '/html/body/div[5]/div/div/div/div[2]/div[1]/ul/li[8]'
    INFRA_ETIME = '//*[@id="report_container"]/div[1]/div[4]/div/span/input'
    INFRA_ETIME_CLEAR = '/html/body/div[6]/div/div/div/div[1]/input'
    INFRA_ETIME_ENTER = '/html/body/div[6]/div/div/div/div[1]/a'
    INFRA_SEARCH = 'button.styles__button-sc-izsc6o-0.gCxuqw'
    INFRA_LISTS = '//*[@id="p-report-node-table"]/tbody[2]/tr'
    
    NETWORK_ANALYTICS = '//*[@id="root"]/div/div/div[1]/div/div[4]/div/div[3]/div/div/div[3]/a[3]'
    NETWORK_METRICS = '//*[@id="root"]/div/div/div[1]/div/div[4]/div/div[3]/div/div/div[3]/a[4]'
    NETWORK_STIME = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[1]/div[1]/div[2]/div/div/div/div/div[1]/div[1]/div[1]/div/div[6]/input'
    NETWORK_INTERVAL = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[1]/div[2]/div[2]/div/div/div/div'
    NETWORK_COMMON_INTERVAL = '/html/body/div[4]/div/div/div/ul/li[1]'
    NETWORK_NETWORK = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[2]/div[1]/div[2]/div/div[2]/div[5]/button/div'
    NETWORK_IN = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[2]/div[1]/div[2]/div/div[2]/div[5]/div/button[1]/span'
    NETWORK_OUT = '//*[@id="whatap_layout_background_dom"]/div/div/div/div[2]/div[1]/div[2]/div/div[2]/div[5]/div/button[2]/span'
    NETWORK_IN_MAX = 'div.counterstyle__info-sc-1s8kj3m-10.dTGKQj span'
    NETWORK_OUT_MAX = 'div.counterstyle__info-sc-1s8kj3m-10.dTGKQj span'
    NETWORK_IN_CLOSE = 'button.styles__button-sc-izsc6o-0.cmenzf.whatap-ant-dropdown-trigger.ants__dropdown-sc-wx3unj-26.responsiveoptionbarstyle__styleddropdown-sc-3c2fpk-3.iqrcpy.dfmrxn'
    NETWORK_IN_CLOSE2 = 'button.styles__button-sc-izsc6o-0.fisbbf div.styles__wrapper-sc-er8sh9-0.hpbyug'